'use client';
import Image from 'next/image';
import { useEffect, useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { BatteryCharging, BrainCircuit, CarFront, Gauge, Layers3, RadioTower, Route, SunMedium, Wrench, Zap } from 'lucide-react';
import { buttonVariants } from '@/components/ui/button';
import { cn } from '@/lib/utils';

gsap.registerPlugin(ScrollTrigger);
const problems=[['Тривале заряджання електромобілів',BatteryCharging],['Нестача зарядних станцій',RadioTower],['Неефективний транспортний потік',Route],['Старіння інфраструктури',Wrench]];
const steps=[['01','Модульні дорожні панелі','Сегменти швидко монтуються, діагностуються та замінюються без зупинки міста.',Layers3],['02','Бездротова індукційна зарядка','Енергія передається в русі точно під авто, коли це потрібно.',Zap],['03','AI-система управління трафіком','Алгоритми балансують потік, навантаження та споживання енергії в реальному часі.',BrainCircuit]];
const tech=[['Модульна структура',Layers3],['Бездротова зарядка',Zap],['Smart Road AI',BrainCircuit],['LED-розмітка',Gauge],['Сонячна інтеграція',SunMedium]];
const stats=['0 зупинок для зарядки','40% ефективніший транспортний потік','Розумний розподіл енергії','Зменшення CO₂ викидів'];
const roadmap=['2026 — Створення прототипу','2028 — Пілотне smart-city місто','2030 — Інтеграція в автомагістралі','2035 — Глобальне масштабування'];
const team=['Максим Лисак — розробник сайту','Богдан Михненко','Воловенко Валерія','Володимир Горовий','Роздобудько Захар'];
export default function Home(){const root=useRef<HTMLElement>(null); useEffect(()=>{const ctx=gsap.context(()=>{gsap.from('.reveal',{opacity:0,y:28,duration:.9,stagger:.12,ease:'power3.out',scrollTrigger:{trigger:'.reveal',start:'top 92%'}}); gsap.utils.toArray<HTMLElement>('.section').forEach(s=>gsap.from(s,{opacity:0,y:45,duration:1,scrollTrigger:{trigger:s,start:'top 82%'}})); gsap.to('.particle',{y:-28,x:12,repeat:-1,yoyo:true,duration:3,stagger:.35,ease:'sine.inOut'}); gsap.fromTo('.pulse-line',{scaleX:.25,opacity:.2},{scaleX:1,opacity:1,repeat:-1,yoyo:true,duration:2.2,ease:'sine.inOut'});},root); return()=>ctx.revert()},[]);
return <main ref={root} className='overflow-hidden bg-[#07111F] text-white'>
<header className='fixed inset-x-0 top-0 z-50 mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-12'><a href='#top' className='font-semibold tracking-[.24em]'>VOLTWAY</a><nav className='hidden items-center gap-6 text-sm text-slate-300 md:flex'><a href='#technology' className='hover:text-cyan-200'>Технологія</a><a href='#vision' className='hover:text-cyan-200'>Бачення</a><a href='#roadmap' className='hover:text-cyan-200'>План</a><a href='#team' className='hover:text-cyan-200'>Команда</a></nav></header>
<section id='top' className='relative min-h-screen flex items-center px-6 md:px-12 lg:px-20'>
<Image src='/images/hero-road.webp' alt='Футуристична дорога VoltWay' fill priority className='object-cover object-center'/><div className='absolute inset-0 bg-[linear-gradient(90deg,#07111F_8%,rgba(7,17,31,.72)_48%,rgba(7,17,31,.35))]'/><div className='energy-grid absolute inset-0'/>
<div className='absolute inset-x-0 bottom-16 mx-auto h-px w-[70%] road-line pulse-line origin-center'/>{[...Array(5)].map((_,i)=><span key={i} className='particle absolute h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_18px_#0EA5FF]' style={{left:`${12+i*10}%`,top:`${18+(i%4)*14}%`}}/>)}
<div className='relative z-10 max-w-2xl'><p className='reveal mb-5 text-sm uppercase tracking-[.35em] text-cyan-200/80'>Інфраструктура нового покоління</p><h1 className='reveal text-glow text-6xl font-semibold tracking-tight md:text-8xl'>VoltWay</h1><p className='reveal mt-5 text-xl text-slate-200 md:text-2xl'>Дороги, що заряджають майбутнє</p><div className='reveal mt-9 flex flex-wrap gap-3'><a href='#technology' className={cn(buttonVariants({size:'lg'}))}>Дослідити технологію</a><a href='#vision' className={cn(buttonVariants({size:'lg',variant:'outline'}))}>Наше бачення</a></div></div>
</section>
<section className='section px-6 py-24 md:px-12 lg:px-20'><Header kicker='Виклик' title='Мобільність уповільнює себе сама' /><div className='mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4'>{problems.map(([t,I])=>{const Icon=I as typeof Zap; return <div key={t as string} className='glass rounded-3xl p-6 transition hover:-translate-y-1 hover:border-cyan-300/50'><Icon className='mb-8 text-cyan-300'/><p className='text-lg'>{t as string}</p></div>})}</div></section>
<section id='technology' className='section px-6 py-24 md:px-12 lg:px-20'><Header kicker='Як це працює' title='Не асфальт. Інтелектуальна енергетична платформа.' /><div className='mt-10 grid gap-6 lg:grid-cols-[1.05fr_.95fr]'><div className='glass relative min-h-[420px] overflow-hidden rounded-[2rem] p-6'><div className='energy-grid absolute inset-0 opacity-70'/><div className='scanline absolute inset-x-0 h-28'/><div className='relative flex h-full flex-col justify-between'><div className='flex items-center justify-between text-xs uppercase tracking-[.28em] text-cyan-200'><span>Схема дороги</span><span>Живий потік енергії</span></div><div className='relative mx-auto flex h-64 w-full max-w-md items-center justify-center'><div className='orbit absolute h-56 w-56 rounded-full border border-cyan-300/25'/><div className='absolute h-40 w-40 rounded-full border border-violet-300/20'/><div className='glass z-10 rounded-3xl px-8 py-6 text-center'><CarFront className='mx-auto mb-3 text-cyan-200'/><p className='font-medium'>Електромобіль у русі</p></div><div className='absolute bottom-7 left-1/2 h-1 w-[80%] -translate-x-1/2 road-line'/><div className='absolute bottom-3 left-1/2 grid w-[84%] -translate-x-1/2 grid-cols-5 gap-2'>{tech.map(([t])=><span key={t as string} className='h-8 rounded-lg border border-cyan-300/20 bg-cyan-300/10'/>)}</div></div><p className='max-w-md text-sm text-slate-300'>Панелі активуються лише під транспортом, передають енергію безконтактно та постійно звітують AI-системі про стан полотна.</p></div></div><div className='grid gap-4'>{steps.map(([n,t,d,I])=>{const Icon=I as typeof Zap; return <div key={t as string} className='glass rounded-3xl p-5 transition hover:-translate-y-1 hover:border-cyan-300/50'><div className='flex items-start gap-4'><span className='text-cyan-300'>{n as string}</span><Icon className='mt-1 shrink-0 text-violet-300'/><div><h3 className='text-lg font-medium'>{t as string}</h3><p className='mt-2 text-sm text-slate-300'>{d as string}</p></div></div></div>})}</div></div><div className='mt-6 grid gap-4 md:grid-cols-5'>{tech.map(([t,I])=>{const Icon=I as typeof Zap; return <div key={t as string} className='glass rounded-2xl p-4'><Icon className='mb-8 text-cyan-300'/><p className='text-sm'>{t as string}</p></div>})}</div></section>
<section className='section px-6 py-24 md:px-12 lg:px-20'><div className='grid gap-4 md:grid-cols-2 lg:grid-cols-4'>{stats.map((s,i)=><div key={s} className='glass rounded-3xl p-6'><div className='mb-5 text-4xl font-semibold text-cyan-300'>{i===0?'0':i===1?'40%':'AI'}</div><p className='text-slate-200'>{s}</p></div>)}</div></section>
<section id='roadmap' className='section px-6 py-24 md:px-12 lg:px-20'><Header kicker='Дорожня карта' title='Від прототипу до глобальної мережі' /><div className='mt-10 space-y-4'>{roadmap.map(r=><div key={r} className='glass rounded-2xl p-5'>{r}</div>)}</div></section>
<section id='vision' className='section relative min-h-[82vh] px-6 py-24 md:px-12 lg:px-20'><Image src='/images/future-city.webp' alt='Місто майбутнього' fill className='object-cover'/><div className='city-glow absolute inset-0'/><div className='absolute inset-0 bg-[linear-gradient(90deg,#07111F,rgba(7,17,31,.4),#07111F)]'/>{[...Array(6)].map((_,i)=><span key={i} className='particle absolute h-1.5 w-1.5 rounded-full bg-cyan-200 shadow-[0_0_18px_#0EA5FF]' style={{left:`${8+i*9}%`,top:`${20+(i%5)*12}%`}}/>)}<div className='relative flex min-h-[62vh] max-w-3xl flex-col justify-end'><Header kicker='Місто майбутнього' title='Мережа, у якій дорога передає енергію, дані та напрямок розвитку' /><p className='mt-6 max-w-2xl text-lg leading-8 text-slate-200'>Ми віримо, що дороги майбутнього повинні не лише з’єднувати міста, а й передавати енергію, дані та створювати нову інфраструктуру для електричного транспорту.</p><div className='mt-8 grid gap-3 sm:grid-cols-3'><span className='glass rounded-2xl p-4'>Автономні авто</span><span className='glass rounded-2xl p-4'>Підключені магістралі</span><span className='glass rounded-2xl p-4'>Зелена енергія</span></div></div></section>
<section id='team' className='section px-6 py-24 md:px-12 lg:px-20'><Header kicker='Команда' title='Люди, які перетворюють дорогу на платформу' /><div className='glass mt-8 max-w-4xl rounded-3xl p-6 text-slate-200'><p className='text-lg leading-8'>VoltWay — стартап учнів ВСП «Оптико-механічний фаховий коледж КНУ імені Тараса Шевченка», спеціальність «Інженерія програмного забезпечення», 1 курс.</p></div><div className='mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-5'>{team.map((m,i)=><div key={m} className='glass rounded-3xl p-5 text-center transition hover:-translate-y-1'><div className='mx-auto mb-5 flex h-20 w-20 items-center justify-center rounded-full bg-gradient-to-br from-cyan-300/30 to-violet-500/30 shadow-[0_0_30px_rgba(14,165,255,.22)]'><CarFront className='text-cyan-100'/></div><p className='text-sm text-slate-200'>{m}</p>{i===0&&<span className='mt-3 inline-block text-xs text-cyan-300'>Розробник сайту</span>}</div>)}</div></section>
<section className='section px-6 py-28 text-center md:px-12 lg:px-20'><h2 className='mx-auto max-w-4xl text-3xl font-semibold leading-tight md:text-6xl'>Ми не будуємо дороги.<br/>Ми будуємо енергетичну систему майбутнього.</h2><a href='#top' className={cn(buttonVariants({size:'lg'}),'mt-10')}>Приєднатися до майбутнього</a></section>
</main>}
function Header({kicker,title}:{kicker:string,title:string}){return <><p className='text-sm uppercase tracking-[.3em] text-cyan-300'>{kicker}</p><h2 className='mt-4 max-w-3xl text-3xl font-semibold tracking-tight md:text-5xl'>{title}</h2></>}
